name: Build, Test, and Verify CustomerSearch Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Step to checkout the code from the repository
        uses: actions/checkout@v2

      - name: Setup .NET  # Set up .NET SDK for building and testing the project
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Restore dependencies for main project
        run: dotnet restore CustomerSearch/CustomerSearch.csproj

      - name: Restore dependencies for test project
        run: dotnet restore CustomerSearch/CustomerSearch.Tests/CustomerSearch.Tests.csproj

      - name: Build CustomerSearch service
        run: dotnet build CustomerSearch/CustomerSearch.csproj --configuration Release

      - name: Run tests
        run: dotnet test CustomerSearch/CustomerSearch.Tests/CustomerSearch.Tests.csproj --no-build --verbosity normal

      - name: Publish CustomerSearch service
        run: dotnet publish CustomerSearch/CustomerSearch.csproj -c Release -o ./publish

      - name: Verify service is running
        run: |
          dotnet ./publish/CustomerSearch.dll &  # Start the service in the background
          sleep 10  # Wait 10 seconds to allow the service to start
          curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/api/customer/search | grep 200
        shell: bash
